### ISSUE TITLE
Can't start scheduleR [Mac OSX]

### ISSUE THREAD

**Issue by mhnierhoff** [Bart6114/scheduleR#7]
Great tool and idea. Sadly, scheduleR won't start on my Mac.
Imho all components have been correctly installed. 
Error logs are attached.

npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.6.1
3 info using node@v0.10.35
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart scheduler-for-r@0.0.12
6 info start scheduler-for-r@0.0.12
7 verbose unsafe-perm in lifecycle true
8 info scheduler-for-r@0.0.12 Failed to exec start script
9 verbose stack Error: scheduler-for-r@0.0.12 start: `node bin/scheduler.bin.js`
9 verbose stack Exit status 8
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:98:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:98:17)
9 verbose stack     at maybeClose (child_process.js:766:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
10 verbose pkgid scheduler-for-r@0.0.12
11 verbose cwd /Users/mhn/scheduleR
12 error Darwin 14.1.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.10.35
15 error npm  v2.6.1
16 error code ELIFECYCLE
17 error scheduler-for-r@0.0.12 start: `node bin/scheduler.bin.js`
17 error Exit status 8
18 error Failed at the scheduler-for-r@0.0.12 start script 'node bin/scheduler.bin.js'.
18 error This is most likely a problem with the scheduler-for-r package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node bin/scheduler.bin.js
18 error You can get their info via:
18 error     npm owner ls scheduler-for-r
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

```
Hardware:

    Hardware Overview:

      Model Name: MacBook Air
      Model Identifier: MacBookAir4,2
      Processor Name: Intel Core i5
      Processor Speed: 1,7 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 3 MB
      Memory: 4 GB

Software:

    System Software Overview:

      System Version: OS X 10.10.2 (14C109)
      Kernel Version: Darwin 14.1.0
      Boot Volume: Macintosh HD
(...)
```

**Comment by Bart6114** [comment]
Thanks for testing @mhnierhoff.

Could you also post the output printed in the console when starting scheduleR? You're sure you have a running mongodb instance and the url specification for it in ```user.config.json``` is correct?

**Comment by mhnierhoff** [comment]
Mongodb is up and running, user.config.json is correctly specified, attached you'll find the console output.
```
Maximilians-MacBook-Air:scheduleR mhn$ npm start

> scheduler-for-r@0.0.12 start /Users/mhn/scheduleR
> node bin/scheduler.bin.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mhn/scheduleR/config/init.js:6:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.35
npm ERR! npm  v2.6.1
npm ERR! code ELIFECYCLE
npm ERR! scheduler-for-r@0.0.12 start: `node bin/scheduler.bin.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the scheduler-for-r@0.0.12 start script 'node bin/scheduler.bin.js'.
npm ERR! This is most likely a problem with the scheduler-for-r package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/scheduler.bin.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls scheduler-for-r
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mhn/scheduleR/npm-debug.log
Maximilians-MacBook-Air:scheduleR mhn$ open npm-debug.log
```

**Comment by Bart6114** [comment]
this seems like the ```glob``` module hasn't been installed.

Did you run ```npm install``` while in the scheduleR directory (could require admin rights)? What was the output?

**Comment by mhnierhoff** [comment]
Okay I installed glob, then I got the error message for the following packages and installed them all: lodash, mongoose, express, morgan, body-parser, express-session, compression, method-override, cookie-parser, helmet, passport, connect-mongo, connect-flash, consolidate, connect-multiparty, cron, temp, async, node mailer, swig, marked, request and finally passport-local.

Now I get this error message:
```
undefined:25
    "url": "mongodb://abcd:abcd@ds039351.mongolab.com:39351/scheduler“
                                                                      ^
SyntaxError: Unexpected token
```
Connecting to this mongodb via shell works fine. (abcd is not the real dbuser and password) ;)

**Comment by mjlassila** [comment]
The last error (Error: listen EADDRINUSE) is thrown because the address scheduleR uses is already in use. Please check if the node is running (ps aux | grep node) and kill it (kill -9 [pid-of-node-process], then try npm start again. I got this same error after upgrading scheduleR because I forgot to stop the running node process beforehand.

**Comment by Bart6114** [comment]
Agreed @mjlassila, this seems like some other process in running on the specified port. I'll add error handling for these situations (so that a clear output is given on what is going on) to my TODOs.

@mhnierhoff, can you verify that this is indeed the problem?

**Comment by mhnierhoff** [comment]
@mjlassila You were right. After killing the node process and restarting it finally works. Thanks a lot for the great help - @Bart6114 & @mjlassila

**Comment by Bart6114** [comment]
Thanks for verifying
